PRO PN PN PN PN
PRO NN PN PN
PRO PN PN PN
PRO PN PN
PRO PN
PRO NN PN PN
PRO PN PN
CD SYM CD NN DT IN NN
PRO PN PN PN
PRO PN PN
DT VB PN
PRO PN
PRO PN PN
PRO NN PN
PRO PN
PRO AUX VB IN SYM SYM CC VB IN IN IN PRO VB NN NN NN IN NN NN SYM KAN
PRO IN PRO VB NN NN RB CC PRO RB AUX VB NN DT PRO RB JJ VB SYM KAN
PRO PN
PRO PN
PRO PN PN
PRO PN
PRO PN
NN PN VB NN RPN VB JJ NN NN CC NN JJ RB CD NN RB VB NN NN JJ IN PN RB KAN
PRO NN PN PN
NN NN VB JJ RB RB RB VB VB RB CC NN JJ RB VB VB IN NN RPN VB NN JJ JJ DT PA KAN
PRO PN
PRO PN PN
VB JJ VB VB VB JJ IN NN IN IN NN IN NN DT KAN
PRO PN AUX VB VB RB RB IN SYM SYM NN PRO RB VB RB RB RB JJ NN DT PA KAN
PRO NN PN PN
PRO PN PN PN
PRO PN PN AUX VB VB IN NN PN CC AUX VB IN NN NN PRO VB NN RB RB JJ CC IN NN JJ DBL KAN
NN PN VB IN SYM NN PRO VB PRO NN PRO NN RB AUX VB SYM SYM PRO PN VB IN SYM RB VB IN PRO NN PRO NN RB AUX VB PA SYM
DT VB PN PN
CC NN NN DT CD DT IN NN RB AUX VB IN VB NN NN RB JJ RB CC VB NN NN NN PN RB JJ KAN
PRO PN
PRO PN
IN NN DT RB NN JJ IN NN IN PRO PN PN CC PRO PN IN NN VB_JJ PA CC PRO DT CD DT AUX VB IN NN IN CD NN KAN
NN RB PRO VB IN PRO RPN VB NN RB VB IN SYM VB VB VB IN NN NN IN NN NN CD NN AUX VB VB NN NN PN PN DT SYM KAN
PRO PN
PRO PN
NN CD VB NN CD PN IN NN NN PN IN NN NN PN AUX VB IN SYM SYM NN PN VB NN NN PN IN NN NN VB RB JJ IN NN NN RPN VB NN NN IN NN SYM SYM KAN
PRO NN PN
PRO PN PN
PRO NN PN PN
PRO PN PN
DT VB PN PN
PRO PN
PRO PN PN
IN VB NN PN RB JJ VB NN VB NN CD PRO DBL JJ PRO PA VB PRO VB NN IN VB IN NN CD NN RB RB VB NN NN VB IN VB IN NN NN NN DT KAN
PRO NN PN PN
PRO PN PN
PRO PN
DT VB PN
PRO PN PN PN
PRO PN
PRO PN
PRO PN PN
PRO NN PN PN
PRO PN
PRO PN PN PN
PRO PN PN
PRO PN PN PN
PRO PN
PRO NN PN
IN VB NN IN NN DT NN AUX VB NN IN NN CC VB NN DT IN NN RPN VB IN NN NN NN NN NN CD IN NN NN NN IN VB NN IN JJ NN NN CD KAN
VB NN DT RB RB RB VB IN NN RPN NN NN DT AUX VB DT PA KAN
NN JJ DBL VB VB SYM CD SYM VB NN NN NN NN IN NN RPN VB NN PN CD SYM
PRO PN
PRO PN
PRO PN PN
DT VB NN JJ RB RPN NN DT AUX VB NN DT VB IN NN VB NN NN PN RB IN VB IN NN PN VB IN VB NN NN DT AUX VB VB NN PN CC VB IN PRO VB IN NN PN IN NN CD RPN JJ RB IN NN NN KAN
PRO PN PN PN
PRO NN PN
PRO PN PN
VB_JJ IN NN NN AUX VB IN NN NN IN NN JJ IN NN NN RPN VB NN VB_JJ RPN NN JJ CD DT VB VB NN RPN VB VB VCOM IN JJ IN VB NN NN IN VB NN PN KAN
PRO PN PN
PRO PN PN
DT VB PN PN
PRO PN
PRO PN PN PN
NN JJ DT AUX VB VB RB PRO AUX VB IN NN NN NN CD NN CC VB IN NN CD PN PN IN NN RB KAN
PRO PN PN
PRO PN
PRO PN
PRO PN PN PN
PRO NN PN PN
IN NN NN IN NN IN PRO PN PRO PN PN PN NN NN NN AUX VB NN JJ IN NN IN PRO NN NN CC AUX VB IN NN VB NN VB NN JJ CC NN NN KAN
DT VB PN
PRO PN
PRO PN PN
PRO PN PN
PRO PN PN
PRO PN PN PN NN NN PN AUX VB IN NN CD M IN DT VB DT IN NN RPN PRO IN NN PN PN PN VB NN PN VB RB IN NN PN VB VCOM IN VB NN NN NN JJ NN KAN
PRO PN JJ VB IN SYM PRO RB RB VB PA SYM KAN
PRO PN PN PN
PRO PN
PRO NN PN PN PN
PRO PN PN
PRO NN PN PN
PRO NN PN PN
PRO PN PN
PRO NN PN PN
PRO NN PN
PRO PN PN
PRO PN
PRO PN PN
PRO NN PN
RB NN NN VB_JJ NN NN NN CD PN RB PRO VB VB CD PN RB KAN
DT VB PN
PRO RB RPN RB VB IN NN NN IN RB VB IN PRO RPN VB NN CC VB_JJ NN DT PRO DT AUX VB NN VB VB NN KAN
PRO PN
PRO PN PN
IN NN NN IN PRO SYM NN NN DT VB IN VB VB IN NN NN IN NN NN IN NN CC IN VB NN VB RB IN NN JJ RB IN KAN
PRO PN PN
PRO PN PN
PRO NN PN PN
IN IN NN NN PN RB AUX VB NN RB JJ RB IN NN VB NN PN JJ IN NN PN DT KAN
PRO PN
PRO NN PN PN
PRO NN PN
PRO PN PN PN
IN NN VB NN IN NN NN DT VB NN NN IN JJ DT NN VB NN NN VB_JJ RB JJ NN JJ NN NN RB VB NN CC NN RB VB NN CC VB NN NN VB_JJ NN KAN
PRO NN PN PN
PRO PN PN
DT VB PN PN PN
PRO PN PN
PRO PN PN
PRO NN PN
DT VB PN PN
PRO NN PN
PRO NN PN PN
PRO NN PN
PRO PN
PRO NN PN PN
PRO PN
PRO PN
PRO PN
IN NN VB_JJ IN NN NN AUX VB NN NN CD NN IN NN CD PN IN NN NN VB NN CC RB RB PA NN NN DT AUX VB NN RB CC PRO AUX VB VB NN CD NN RB RB RB RB VB NN NN VB KAN
PRO PN
PRO PN PN
DT VB PN
DT VB PN
PRO PN
PRO AUX VB PRO NN IN CC NN RB VB RB VB RB RB NN DT RB JJ RB RB PA KAN
PRO PN PN PN
NN VB NN IN SYM DT RB SYM VB NN PRO PRO VB IN VB SYM KAN
IN NN PN NN DT CD M AUX VB NN CC NN VB_JJ NN IN NN NN RPN AUX VB IN NN NN DT VB_JJ NN VB_JJ VB_JJ NN IN NN CC NN NN KAN
PRO PN PN PN
PRO NN PN
NN RB JJ JJ PA KAN
NN CD AUX VB IN NN NN IN PN IN NN JJ NN NN NN IN IN VB NN RPN VB IN NN IN NN NN VB_JJ RB CC NN RB IN VB NN KAN
NN DT AUX VB VB NN PN KAN
NN CC NN IN NN PN AUX VB VB IN NN RPN VB NN IN NN NN CC NN NN IN IN NN IN NN CC NN DT KAN
PRO PN PN
PRO PN PN
NN RB RB NN SYM NN RB RB NN RB RB VB NN NN NN JJ NN NN IN NN PA KAN
PRO PN
PRO PN
RB IN NN NN IN NN DT CD VB_JJ IN NN PN RB RB RB VB NN RPN VB VB IN VB IN NN JJ JJ JJ RB PA KAN
PRO NN PN PN
PRO PN
PRO PN
IN NN IN NN NN NN NN PN VB VB IN NN DT VB PRO VB VB IN NN DT IN NN DT IN JJ JJ KAN
IN PRO NN RB VB NN NN NN CD M RB CC PRO VB VB NN IN DT NN DT IN VB RB VB IN NN CD IN NN NN NN RB IN NN NN KAN SYM
PRO PN VB NN NN JJ DT NN DT NN RB VB PRO PN IN SYM VB NN PRO VB PRO PN SYM SYM
PRO PN
PRO PN PN
DT VB PN PN
PRO PN
PRO PN
PRO PN PN
PRO PN
PRO NN PN PN
PRO PN
PRO NN PN PN
NN CC VB NN NN NN RB AUX VB RB IN NN KAN
NN PRO DT RB AUX VB PRO IN NN NN RB PA KAN
PRO NN PN
PRO NN PN PN PN
NN NN NN DT VB RB VB NN IN NN DT NN RB VCOM PA RB NN DT CD M RB VB NN RB VB IN NN NN DBL NN CD VB IN SYM NN PRO VB IN NN PRO PA NN DT VB VB NN DT IN PRO SYM
PRO PN PN PN
DT VB PN PN
PRO PN PN
DT VB PN
PRO PN PN
PRO PN
PRO PN
PRO NN PN PN
NN NN NN NN AUX VB IN NN DT IN DT NN IN NN SYM
PRO PN
PRO PN PN PN
PRO PN PN
PRO PN
PRO NN PN
PRO PN
PRO PN PN VB NN JJ CC NN JJ IN NN KAN
PRO PN PN PN
DT VB PN
NN VB IN SYM UH NN RB JJ SYM VB PRO VB RB SYM KAN
PRO PN PN
NN PRO VB NN VB IN NN DT CD M DT IN SYM NN CC NN DT PRO VB IN PRO SYM SYM
PRO PN PN PN
PRO PN PN NN AB AUX VB IN PN IN SYM SYM PRO AUX VB NN NN JJ IN PN IN VB RB PRO VB IN NN NN NN JJ AUX VB IN PN IN PN NN CD RB NN VB_JJ NN JJ AUX VB RB IN NN CD NN SYM KAN
PRO NN PN PN
PRO NN PN PN PN
PRO NN PN PN VB NN VB_JJ RPN VB NN CD VB PN CC PN CC PRO PN PN VB_JJ NN VB_JJ NN PN AUX VB IN NN PN IN PN NN JJ IN VB VB IN NN IN NN NN NN IN NN PA IN NN IN VB RPN VB IN NN NN NN NN KAN
IN NN DT PA VB NN JJ NN JJ NN VB VB VB VCOM JJ NN KAN
PRO PN
PRO PN PN
PRO NN PN
PRO PN PN
PRO PN
PRO NN PN PN
PRO NN PN PN PN
PRO VB IN SYM SYM IN NN PRO AUX VB IN VB NN NN JJ RB VB IN NN IN NN IN NN IN DT KAN SYM
PRO PN PN
PRO PN
PRO NN PN
PRO NN PN PN
PRO PN
PRO PN PN
NN IN PN AUX VB NN DT NN JJ KAN
NN NN NN JJ RB CC NN NN VB NN VB IN VB NN KAN
PRO PN
PRO NN PN PN PN
PRO PN
VB RB NN VB NN NN IN SYM VB NN SYM RB PRO PA PRO VB IN NN VCOM SYM KAN
IN PRO DT PRO DT VB NN CD IN VB PRO RPN PRO VB VB IN NN NN NN NN CC NN IN PRO RPN VB NN KAN
PRO PN
NN NN DT CD M DT VB NN VB IN PN NN NN VB VB NN KAN
VB RB NN VB_JJ IN PRO PA RPN VB RB KAN
PRO PN
PRO PN PN
DT VB PN
CD NN RB NN DT CD AUX VB IN NN NN CD IN NN NN NN AUX VB VB KAN
NN DT RB RB VB JJ IN NN IN NN NN IN NN NN PN CC NN VB_JJ NN VB NN CD PN NN CD CC NN IN NN NN IN NN NN PN PRO IN NN CD PN NN CD SYM VB NN NN NN VB VB IN NN JJ JJ SYM KAN
PRO NN PN PN
PRO PN
DT VB PN PN
PRO PN
PRO PN
PRO NN PN
PRO PN PN
PRO PN PN
IN NN RB RB RB NN VB VB NN RB RB RB VB DT VB NN NN KAN
PRO PN PN
DT VB PN PN
NN NN JJ DBL IN NN AUX VB NN VB_JJ NN NN NN IN IN VB NN JJ IN PRO IN NN NN PN DT NN IN AUX VB NN IN NN CD SYM CD IN NN NN JJ DBL IN PN IN NN NN IN NN PN IN NN PN JJ KAN
PRO PN PN
PRO NN PN
NN IN PRO PRO PN PN IN NN VCOM NN NN IN VB NN NN VB_JJ NN JJ IN NN PN
PRO PN PN
VB_JJ IN NN VB_JJ NN IN RB PN VB NN NN JJ DBL NN CD NN RB KAN
NN DT PRO VB VB CD NN IN VB NN JJ VB CD NN IN NN NN DT CD NN KAN
PRO PN
RB IN DT VB IN PRO VB IN PN PN AUX VB IN PN PN IN NN DT RB VB NN CC NN RB PA IN VB CD NN DT JJ RB RB NN NN DT VB NN VB_JJ PA VB VB IN VB NN RB JJ KAN
PRO NN PN
PRO PN PN PN
PRO JJ NN NN JJ JJ NN PN IN NN JJ IN NN JJ DBL DT IN NN AUX VB NN NN VB_JJ IN PRO IN PRO IN NN NN CD NN DT KAN
PRO PN PN
PRO PN
PRO PN
PRO PN
DT VB PN
PRO NN PN PN
PRO NN PN PN
DT NN NN NN CD RB VB CC NN NN RB VB VB VB NN DT VCOM KAN
PRO PN PN
NN NN PN PRO PN PN AUX VB IN SYM SYM NN NN VB_JJ NN IN NN AUX VB RB VB PRO JJ IN NN VB_JJ IN NN NN DT PA KAN SYM PRO AUX VB IN SYM SYM NN NN PN VB VB IN NN RPN VB VB VB DT IN RB RB IN NN NN DT PA CC IN NN IN NN NN NN RPN VB VB IN DT PRO KAN PRO VB VB NN VB_JJ NN CC NN IN PRO DT CD DT VB VB VB PRO DT RB SYM KAN
PRO PN
PRO PN PN
NN NN VB NN IN NN RB JJ KAN
NN CD IN RPN VB IN NN IN NN VB NN IN VB NN DT RPN NN VB JJ VB VB IN NN CD NN NN VB NN JJ RB VB VB IN VB NN IN NN JJ DT VB IN NN NN IN NN CD NN RB JJ IN VB KAN
PRO PN PN
PRO PN
PRO PN PN PN
IN NN DT RB PRO JJ NN JJ NN NN IN NN AUX VB IN NN NN NN JJ VB NN JJ IN NN IN VB NN VB NN RB JJ RB IN NN VB NN NN IN VB JJ IN NN CC JJ KAN
NN NN NN DT AUX VB IN NN NN IN NN NN CD SYM CD NN IN NN DT RPN AUX VB VB NN NN CD IN NN NN NN JJ RPN VB NN IN NN PN RB CD JJ RB CD NN IN NN DT VB VB IN NN NN VB_JJ IN NN NN NN PN IN NN JJ KAN
CC NN AB PN PN PN AUX VB VB IN NN DT RB IN PRO AUX VB DT CD NN RB KAN
PRO NN PN PN
PRO PN
PRO PN PN
PRO PN
PRO PN
NN NN IN NN NN PN IN JJ NN NN NN NN
PRO NN PN
PRO VB RB PRO RB VB NN NN IN NN RB VB NN DT VB IN NN IN PRO PRO VB VB NN VB NN NN KAN
PRO NN PN PN
RB NN VB_JJ NN NN NN RPN VB NN JJ RB NN JJ DBL DT PN PN IN NN NN NN CD AUX VB NN NN JJ VB_JJ NN JJ PN IN VB IN NN NN CD KAN
DT VB PN
DT VB PN PN PN
PRO PN PN
PRO PN PN
NN CC NN VB_JJ VB_JJ VB_JJ JJ DBL AUX VB VB RB JJ IN NN RPN VB NN AUX VB CD CD M IN NN RPN AUX VB NN JJ DBL IN PRO IN VB NN IN NN NN CD KAN
PRO PN PN
PRO PN PN
NN VB_JJ VB_JJ VB_JJ PRO DT DT RB VB VB RB KAN
CD SYM NN VB_JJ NN
PRO PN PN PN
IN NN CD IN NN PRO JJ NN NN VB_JJ NN NN JJ NN PN AUX VB NN PN VB_JJ RB JJ CC VB_JJ NN NN PN RB IN NN PN RB IN NN IN PRO IN NN IN PN IN PN KAN
PRO NN PN PN
PRO IN SYM SYM IN NN RB NN NN AUX VB IN VB IN NN VB VB NN RB SYM KAN
NN RPN RB RB AUX VB JJ IN NN PRO RB JJ DT VB NN NN VB PRO VB IN NN PRO CD JJ RPN VB NN JJ IN PRO RB CC NN RB KAN
PRO NN PN
PRO NN PN PN
PRO NN PN PN
PRO PN
PRO PN
PRO PN PN
PRO PN PN
PRO PN PN PN PN
PRO NN PN PN
PRO PN PN
RB DT PRO VB NN NN CD NN NN IN VB NN CC NN NN CC NN NN RPN PRO VB VB NN VCOM DT KAN
IN NN IN PRO JJ NN JJ NN PN IN NN VB_JJ NN NN VB IN PRO NN NN PN PN VB_JJ NN CD PN AUX VB IN NN NN IN NN RPN NN VB JJ IN PN NN CD DT VB AUX VB RB IN NN IN PN IN NN NN CC NN JJ DBL IN NN NN NN RPN PN VB NN NN NN KAN
DT VB PN
CC NN DT NN NN NN CD NN IN IN NN IN PRO PN VB VB NN NN CC VB NN IN NN NN NN IN NN VB VB KAN
PRO PN PN
PRO NN NN VB NN VB NN RB VB NN IN NN JJ CC RB PRO CD VB VB VB RB VCOM PA KAN
PRO PN PN PN
PRO NN PN PN PN
NN IN NN DT VB JJ NN RPN NN AUX VB RB RB IN NN NN NN IN NN NN NN IN PN NN CD CC NN VB_JJ NN NN NN IN NN CC NN RB JJ IN NN CC NN IN NN VB_JJ KAN
PN PN IN NN NN PN CD VB NN CD NN CC VB NN VB_JJ CD NN VB CD NN VB CD CC VB CD RB NN IN PRO PN PN VB NN CD NN CC VB VCOM CD NN VB CD NN VB CD NN VB CD NN RB PRO AUX VB IN NN CD NN KAN
NN IN VB_JJ NN DT RB VB IN NN JJ DBL IN NN PN RB SYM KAN
NN IN NN VB_JJ NN RB JJ RB IN VB NN NN VB NN JJ IN VB NN KAN
PRO PN
PRO PN PN
PRO PN PN VB NN CD NN VB_JJ NN NN IN NN CD NN NN CD NN PN KAN
PRO PN PN
NN NN DT NN PN PN RB AUX VB RB IN NN VB_JJ NN JJ IN NN CC NN IN PN AUX CC AUX VB VB NN RB IN IN NN NN CC PN RB CC VB IN NN CD PA NN IN CD NN RB RPN VB VB KAN
NN CD NN NN VB VB IN VB NN IN NN JJ RPN VB NN NN VB IN NN NN IN NN NN RPN VB VB JJ KAN
PRO PN PN PN
PRO PN
PRO PN PN
PRO PN PN
DT VB PN PN
PRO VB RB VCOM
PRO PN PN
PRO PN PN
IN RB IN PRO DT CD M PRO DT RB VB VB CC VB VB NN NN NN NN CD NN CC VB IN NN CD PN PN IN RB IN NN CD NN IN VB NN KAN
PRO PN PN PN
NN DT VB RB NN NN VB VB IN NN PRO PN PA
PRO PN PN
PRO PN
PRO RPN RB AUX VB IN NN IN NN PN VB NN PN VB IN PN IN NN PN RPN VB NN NN NN CD NN IN NN PN KAN
PRO PN
DT VB PN PN PN
PRO PN PN
PRO NN PN PN PN
PRO PN
PRO PN PN
IN NN IN NN VB NN CD NN RB VB PN IN VB NN DT CD NN CD NN IN JJ CD NN KAN
PRO NN PN PN
PRO PN PN
CC NN PRO JJ NN VB VB VB NN RB VB NN NN NN PRO AUX JJ IN NN NN VB NN KAN
PRO PN PN
PRO NN PN
PRO PN PN
PRO PN PN
PRO NN PN PN
PRO PN
PRO PN PN
JJ IN PRO PN PN CC PN PN PN PRO PN VB VB IN NN NN IN NN IN VB NN NN NN SYM NN CD IN NN NN SYM VB_JJ IN NN NN SYM NN CD CC CD IN NN NN SYM CC VB_JJ NN NN IN VB NN NN NN SYM NN CD IN NN NN SYM RB PRO AUX VB VB NN NN CD NN IN NN CC VB IN NN CD PN PN KAN
PRO NN PN PN
PRO NN PN PN
PRO PN PN
PRO PN
PRO PN PN
PRO PN
IN PN NN CD NN IN NN PN PN VB_JJ NN IN VB VB NN IN SYM VB_JJ NN IN PRO PN PN SYM AUX VB VB NN NN NN CD NN VB IN NN PN IN NN IN NN NN KAN
PRO PN PN
IN NN RPN NN CD JJ VB VB NN IN NN RB VB DT DT RB VB RB NN IN NN VB_JJ NN RB RB RB VB NN VB_JJ NN RB VB_JJ NN NN JJ IN NN NN NN RB VB IN NN NN RB NN RPN NN VB NN NN CC VB NN IN VB NN NN IN NN CC NN IN NN RB VB NN RB JJ KAN
DT VB PN
NN NN CC NN DT VB IN NN IN NN RPN VB NN RB VB NN CC VB IN NN CC NN IN NN KAN
PRO PN
NN CD CC IN NN VB NN NN CD NN IN NN RPN VB NN VB IN JJ RB RB VB VB PRO IN NN DT NN NN NN NN VB VB NN DT CD DT IN NN NN CD IN VB NN KAN
NN RB AUX VB IN NN NN RB RPN VB IN VB NN IN PRO DT KAN
PRO PN
DT VB PN
PRO PN PN PN
PRO PN
PRO PN
PRO PN PN
PRO PN PN
PRO PN
PRO PN PN
PRO PN
NN PRO VB IN SYM NN RB NN RB VB PRO PA SYM RB NN VB IN SYM CC RB RB VB RB PRO VB PRO VB PRO JJ IN NN DT RB RB RB PRO VB IN PRO SYM RB NN VB NN DT IN VB NN DT JJ JJ IN NN RB PRO VB NN IN SYM PRO VB NN PA NN IN PRO RB VB NN IN NN JJ CC PRO VB RB VB VB NN VB NN VB NN SYM
PRO VB RPN VB IN NN PN CC PN VB VCOM JJ KAN
PRO NN PN PN PN PN
PRO PN PN
PRO PN PN
NN VB_JJ PN NN AUX VB IN NN AUX VB NN IN PRO IN NN NN KAN
PRO PN
NN VB_JJ RB VB VB IN PRO RPN VB NN IN RB VB IN NN IN NN NN NN IN NN DT PA KAN
PRO PN
DT VB PN
PRO NN PN
CC PRO RB VB VB DT PA IN NN RB VB NN JJ NN IN PRO VB IN VB NN RB RB KAN
VB_JJ IN NN IN NN NN NN PN CD NN DT VB NN VB NN NN IN PN VB IN NN NN NN CC NN IN NN RB JJ RPN AUX VB IN NN NN JJ RB DT IN NN DT IN NN CC IN NN VB NN VB NN NN CC VB VB NN NN NN KAN
DT VB PN PN
NN NN PN NN CD M AUX VB PN IN PN CC PN NN AUX VB NN NN IN CD NN NN CC NN VB_JJ NN NN CD NN IN NN NN CD M IN NN PN NN PN KAN
PRO NN PN PN
PRO NN PN PN
PRO PN PN
VB NN CD IN CD KAN
IN NN DT NN VB JJ JJ IN PRO KAN
NN NN DT AUX VB IN PN IN SYM SYM NN NN NN CC NN NN NN JJ M IN NN PN RB AUX VB IN QT VB VB PRO PA IN NN RPN PRO VB NN VB_JJ NN NN IN VB NN RPN VB NN KAN SYM
PRO NN PN
PRO PN
PRO PN
PRO PN
PRO NN PN
PRO PN PN
PRO PN
DT VB PN PN
PRO PN PN
IN PRO PN PN CC NN PRO VB VB NN IN VB IN NN IN NN NN JJ CD SYM VB NN NN PN PN DT PA SYM KAN
NN PRO PN RB VB NN NN JJ RB RB VB VB VB
PRO PN
PRO PN
PRO PN
PRO PN
PRO PN PN NN NN PN AUX VB NN IN NN NN JJ NN CC NN NN NN RPN VB IN NN NN CD M RB VB VB VB RB PA CC RB VB NN VB_JJ IN NN KAN
PRO PN PN
PRO PN VB DT NN IN NN IN PRO JJ IN PRO CC NN DT DT VB PRO CC NN VB NN IN PRO KAN
PRO PN
PRO PN PN
PRO NN PN
DT VB PN
PRO PN PN
DT VB PN
DT VB PN PN PN
PRO PN
DT NN DT VB NN CD VB IN NN JJ JJ NN DT VB NN NN NN VB VB NN RPN PRO AUX VB NN IN JJ IN NN KAN
PRO NN PN PN
NN RPN VB IN NN IN NN DBL VB VB VB IN NN IN NN IN JJ
PRO PN
PRO PN PN
DT VB PN PN
PRO PN PN
PRO PN PN PN
PRO PN
DT VB PN PN
PRO PN PN PN
NN DT NN PN PN NN CD NN AUX VB IN NN RPN AUX VB NN NN RB VB VB NN AUX VB PRO IN PRO VB VB NN IN NN VCOM CC PRO VB IN NN IN NN VB_JJ NN KAN
PRO PN
PRO PN PN PN
PRO NN PN PN
NN RPN PRO VB IN NN PN PRO VB VB NN NN IN NN IN NN NN RB IN NN CD NN DT NN RB PRO VB IN NN CD IN CD JJ RB VB VB NN DT KAN
PRO PN PN
PRO PN
PRO PN PN
PRO AUX VB IN NN IN NN VB_JJ NN AUX VB RB JJ IN NN JJ IN NN IN RB VB NN VB_JJ NN DT CC VB VB NN VB_JJ NN JJ DBL VB_JJ IN VB NN KAN
PRO NN PN PN
IN PN NN NN PN NN CD M AUX VB IN JJ IN VB NN CD IN NN NN NN NN VB_JJ IN NN NN NN IN NN PN KAN
PRO PN PN
DT VB PN PN
DT VB PN
PRO NN PN
PRO PN
PRO PN
CC NN PN DT CD M VB VB CC VB NN RB RB RB IN RB VB RB CD M JJ RPN AUX VB NN IN NN JJ KAN
VB NN PN PN NN NN PRO JJ NN NN PN PN NN NN CD JJ NN CD AUX VB VB IN PN CC VB NN NN IN NN NN IN NN VB_JJ NN NN CD RB RB PRO PN PN PN JJ NN NN CC PRO PN PN NN NN NN PN PN AUX VB VB IN NN VB_JJ NN DT IN NN NN IN PRO VB NN RB KAN
PRO PN AUX VB NN VB NN VB RB RB VB IN NN NN VB NN NN PN IN NN NN RB PRO PN VB VB VB NN CC PRO RB VB VB CC VB NN RPN VB VB NN RB
PRO NN PN PN PN
PRO PN PN
PRO PN PN
NN NN PN CC NN NN JJ NN VB_JJ NN NN IN PN AUX VB NN NN NN CD M RB IN NN IN NN JJ NN KAN
PRO PN PN
PRO PN
PRO PN
PRO NN PN
PRO NN PN PN PN
VB NN VB NN AUX VB NN CD JJ
DT VB PN
PRO PN
NN VB NN IN NN JJ RB VB VB VCOM PA CC IN NN VB NN JJ DT RB NN JJ VB VB KAN
DT VB PN PN
PRO PN
PRO PN PN NN NN PN AUX VB IN NN CD M VB VB IN VB JJ NN CC NN RB NN VB_JJ IN PRO VB VB IN NN DT KAN
PRO NN PN PN
PRO PN PN
PRO PN
PRO NN PN PN
PRO PN PN VB RB IN SYM SYM NN CC NN NN RB VB PRO VB NN NN CC PRO VB IN PRO VB VB VCOM IN NN SYM KAN
CC PRO PN RB AUX VB IN NN JJ IN NN PRO PN PN JJ NN AB RB PA IN PRO VB IN NN IN VB NN RB AUX VB RB VB JJ IN NN CD NN PA KAN
IN JJ NN CD NN DT IN NN PN AUX VB RB IN NN NN CD NN IN NN SYM
PRO PN
PRO PN
PRO NN PN
PRO PN PN
PRO PN
PRO PN PN
DT VB PN PN
PRO PN PN PN
PRO PN PN
IN IN PRO PN PN AUX VB NN JJ NN CD IN PRO RB VB NN NN PN IN IN NN DT KAN
PRO PN PN
NN NN DT AUX VB VB IN SYM SYM NN PRO RB RPN VB NN RB JJ RB VB NN CC JJ PRO RPN AUX VB VB IN CC NN DT RB VB NN JJ PA DT PRO VB VB DT PRO DBL DT RB CC PRO VB NN JJ PRO DBL AUX RB PRO DT PA SYM KAN
PRO PN PN
PRO PN PN
PRO PN PN
PRO PN
PRO PN PN
PRO PN PN PN
DT VB PN PN
PRO PN
NN CD PN NN CD SYM NN NN PN NN CC VB_JJ NN NN SYM PN SYM VB NN RB IN NN IN NN NN RPN IN NN NN IN NN IN DT NN DT IN PRO IN NN CD VB_JJ IN VB NN CD NN IN NN NN RPN RB VB NN JJ CC NN NN IN NN NN CD IN VB IN NN JJ KAN
PRO PN PN
NN IN NN DT VB NN CD RB JJ KAN
PRO PN PN
PRO PN
PRO NN PN
PRO PN PN
PRO PN
IN VB VCOM NN JJ RB PRO RB VB NN PRO IN VB NN DT IN VB NN PRO KAN
DT VB PN PN
NN NN PN PRO VB RB VB NN RPN AUX VB NN RB VB NN PA IN JJ NN IN VB IN NN JJ VB NN VB IN PRO PN PN PA KAN
CC JJ PN PN VB NN NN VCOM JJ CD NN NN DT PN VB JJ IN RB JJ RB VB IN VB VB VB VB IN CD NN AUX KAN
DT VB PN
PRO PN PN PN
PRO PN PN
NN IN NN RB VB NN IN NN RPN NN AUX VB VB NN IN NN JJ CD AB NN VB_JJ NN VB VB NN IN NN NN NN RB JJ CD
PRO PN PN
PRO PN
NN VB_JJ NN AUX VB RB IN NN AUX VB IN NN VB IN CD PN IN CD PN IN NN VB NN NN VB NN IN NN IN CD IN CD PN IN NN IN NN VB IN NN NN SYM NN NN SYM VB IN VB NN VB PN IN NN CC AUX VB NN NN NN IN CD CD PN IN CD CD PN DT NN KAN
PRO AUX VB RB IN SYM SYM NN DT AUX VB NN IN CD NN IN NN PN VB VB NN JJ VB IN NN CD SYM KAN
PRO PN PN NN VB IN NN NN NN AUX VB IN SYM SYM NN IN NN NN IN PRO PN AUX RB VB VB NN NN PN VB CC VB PA DT PA KAN
IN NN IN NN VB_JJ DT RB NN VB RB RB VB VB NN IN NN DT IN RB VB NN IN VB PRO RPN VB IN NN IN NN NN DT IN RB NN RB AUX VB NN VB_JJ NN NN VB_JJ NN CC AUX VB NN RPN VB VB NN IN NN PRO DT CD M RPN VB VB IN NN CD CC NN CD PN JJ KAN
PRO VB NN VB VB IN CD NN RB PRO IN NN IN CD NN KAN
RB VB NN CD VB VB IN NN JJ VB IN
PRO NN PN
PRO NN PN
PRO PN PN PN
PRO PN
PRO PN
DT VB PN PN
PRO PN PN
PRO NN PN PN
PRO NN PN PN
PRO PN AUX VB IN SYM SYM PRO VB VB IN NN JJ IN NN CC PRO NN NN PN PN VB VB RB IN NN NN IN PRO PN PN JJ SYM KAN
DT VB PN PN
PRO PN
DT VB PN PN
PRO AUX VB NN NN PN IN NN KAN
NN JJ NN IN NN PN AUX VB IN NN AUX VB NN IN VB NN CC CC VB NN PRO RB JJ IN NN PN IN NN PRO NN JJ DT PA KAN
PRO PN
PRO PN PN NN NN VB_JJ IN NN PN AUX VB IN SYM SYM NN DT VB RB RB VB NN JJ CC JJ IN NN NN SYM KAN PRO AUX VB RB IN SYM SYM IN PRO VB_JJ NN NN IN NN CC NN IN VB NN NN NN CC IN IN PRO DT KAN NN PN PRO VB_JJ VB VB NN RPN VB VB NN RPN VB NN NN NN NN CC NN NN NN RB CD JJ IN PRO VB_JJ NN SYM KAN
PRO PN PN AUX VB IN VB NN IN JJ RB CC AUX VB RB IN IN NN IN VB NN IN PN NN CD JJ KAN
PRO PN PN
PRO PN PN PN
RB CC NN AUX VB RB RB PRO DT VB VB VB NN DT PA CC NN RB VB IN NN KAN
NN PN PRO DT AUX VB NN RB CD NN JJ VB PRO PN PN IN NN PN IN NN NN CD SYM CD SYM CD SYM CD CC CD SYM CD KAN
PRO NN PN PN
PRO PN
CC PRO PRO PN PN NN NN NN AUX VB IN NN NN PRO RB VB VB IN NN NN NN JJ NN DT PA KAN
NN IN NN VB NN RB RB NN IN NN IN NN IN NN NN NN JJ CC RB JJ NN NN NN NN NN IN NN IN NN PRO CC NN NN NN IN VB NN CC VB_JJ IN NN KAN
IN NN DT AUX VB NN JJ RB VB NN IN NN DT RPN VB
PRO NN PN
NN NN IN PRO AUX VB RB IN NN JJ IN RB CC PRO VB NN NN CC NN NN JJ IN NN KAN
NN JJ NN PN PRO VB NN IN IN NN DT PA RB VB VCOM JJ NN CD NN VB NN IN SYM PN SYM VB NN IN NN NN NN KAN
PN SYM NN JJ VB NN VB NN NN NN CC VB NN NN IN VB NN KAN
PRO PN PN
DT VB PN PN PN
RB CC PRO RB VB NN IN NN PRO VB IN VB PA DT VB VB VB PRO DT AUX VB IN NN DT VB RB RB CC PRO RB VB VB RB NN PRO VB RB VB IN RB AUX VB IN NN DT PA SYM KAN
PN PN RB VB VB NN IN PRO PN PN RPN VB NN DT VCOM PA IN NN NN KAN
NN NN NN CC NN IN NN NN IN NN JJ VB NN VB NN IN PRO VB NN KAN
PRO PN PN
PRO PN
PRO PN PN
PRO PN
PRO PN
PRO NN PN
PRO PN
PRO AUX VB NN NN NN NN CC PN IN VB NN NN IN NN IN NN NN NN IN DT NN PN KAN
PRO PN PN PN
DT VB PN
PRO NN PN PN
DT VB PN PN
PRO NN PN
PRO PN
PRO PN
PRO NN PN PN PN
PRO NN PN
PRO PN
PRO PN PN PN
PRO PN PN AUX VB IN NN VB_JJ IN SYM SYM PN PN PN VB VB JJ IN NN SYM CC DT NN VB_JJ CC RB NN VB_JJ IN NN NN NN PA RB VB VB IN NN NN VCOM PA SYM KAN
NN JJ VB NN IN NN VB VB VB NN IN VB NN JJ KAN
NN DT DT NN RPN VB NN NN CC NN NN IN NN VB_JJ NN VB VB NN IN NN NN VB_JJ NN KAN
PRO PN
RB RB VB NN NN NN NN NN CD CD M IN NN KAN
PRO PN
NN NN IN NN NN PN PRO PN PN CC VB JJ NN PN NN AUX VB IN NN PN AUX VB DT DT NN VB NN NN IN NN NN NN NN NN CC PRO VB IN NN DT VB NN IN VB IN NN VB JJ VB NN NN VB NN VB NN IN NN KAN
PRO NN PN
DT VB PN PN
PRO NN PN PN PN
DT VB PN PN
DT VB PN PN
PRO NN PN PN
PRO PN
PRO PN VB IN SYM PRO AUX VB PRO VB RB CC PRO RB AUX VB PRO VB PRO PA SYM KAN
PRO PN PN PN
NN NN NN VB_JJ NN VB NN NN NN RPN AUX VB IN VB NN
PRO NN PN
NN IN NN JJ VB_JJ NN VB IN PRO NN NN NN PRO PN PN IN PN NN CD PN CC PN PN VB IN NN VB IN SYM SYM NN VB_JJ NN NN JJ NN DT VB VB IN PRO NN JJ NN NN DT RPN AUX VB NN VB VB VB NN NN IN RB NN IN NN DT SYM KAN
PRO PN
IN PN NN NN AUX VB RB VB NN CD M IN NN NN PN VB NN IN NN PN KAN
PRO NN PN
PRO PN PN
PRO PN PN
NN NN DT AUX VB PRO VB NN NN CD RPN VB NN JJ NN PN CD NN NN CD NN DT KAN
PRO PN
PRO PN PN
PRO PN PN
DT VB PN
PRO VB IN SYM SYM NN DT CD AUX VB IN NN DT IN VB JJ IN VB DT IN NN IN JJ NN NN NN VB DT VB PRO DBL VB VB DT KAN SYM
NN JJ NN IN NN PN NN NN CD
NN DT CD M VB RB PRO IN SYM VB PRO VB VB CC PRO PRO PRO DT CD M DT RB VB VB NN VB IN NN NN NN RB PRO SYM
PRO PN PN PN
IN NN JJ IN DT NN IN NN VB CD NN KAN
SYM NN PRO VB IN NN PRO VB NN IN DT SYM
PRO PN PN PN
PRO NN PN PN
IN NN JJ NN CD NN RPN AUX VB VB IN PN RB AUX VB IN NN CD NN PN DT PN PN CC PN PN AUX VB IN NN NN CD IN NN CD CC VB CD NN KAN
PRO PN
PRO PN
PRO PN PN
PRO PN PN
IN VB NN DT RB PRO RB VB NN RB IN RB KAN
PRO NN PN PN
PRO PN PN PN
PRO PN PN
PRO PN PN PN
PRO PN
PRO PN PN
PRO PN PN PN
NN RB VB PN IN SYM PRO VB IN NN PRO DBL RPN AUX VB IN PA SYM SYM KAN
PRO PN
PRO PN PN
DT VB PN PN
PRO PN
NN CC NN NN IN NN PN PRO DT RPN AUX VB IN NN JJ AUX VB IN SYM SYM NN DT VB NN NN NN PN DT RB JJ RB SYM KAN
PRO PN PN PN
PRO PN PN
PRO PN PN
PRO PN
QT NN PN JJ RB VB IN NN NN PA PRO SYM
PRO PN
PRO PN
PRO PN PN
PRO NN PN
NN JJ NN NN PN AUX VB PRO PN PN VB IN NN RB VB PRO RB RPN VB NN IN NN VB_JJ NN VB VB VB IN IN CD M KAN
NN VB IN SYM IN RPN PN PRO VB QT VB PRO NN RB SYM SYM KAN
PRO NN PN PN
PRO NN PN
PRO PN PN
PRO PN PN
PRO NN PN PN
PRO PN PN PRO PRO PN CC PRO PN PN VB VB IN NN NN CC NN JJ PRO PN PN RB NN VB_JJ CD M RB VB PRO PN PN CC PRO PN PN AUX VB VB IN NN PN NN JJ KAN
PRO PN
PRO NN PN PN PN
PRO PN PN
PRO PN PN
DT VB PN
PRO PN
DT VB PN
NN NN VB VB NN PRO RPN JJ VB NN JJ JJ VB VB NN IN NN VCOM NN AUX VB NN IN VB NN DT IN VB VB NN VB NN PRO KAN
PRO NN PN
IN PRO PN VB JJ NN RB VB NN VB VB VB NN IN NN NN IN VB VB NN NN VB NN IN SYM VB RB IN JJ IN NN PRO PRO AUX VB NN VB IN JJ RB CD M PRO SYM
PRO PN
PRO PN PN
PRO NN PN PN
RB NN PRO VB DT VB VB RB VB NN DT VB RB SYM
PRO NN PN PN
PRO PN
PRO PN
NN PN SYM NN NN IN PN PN VB VB IN NN NN NN KAN
PRO PN PN
NN RB VB NN RB JJ KAN
PRO NN PN PN
PN VB RB VB NN CD PN VB KAN
PRO PN
PRO NN PN
PRO PN PN
PRO PN PN
NN PN SYM PN PN IN NN NN NN NN VB_JJ NN VB VB IN VB VB IN NN NN JJ PN NN PN IN NN NN CD NN NN PN PN PN IN NN PN PN VB_JJ NN VB VB IN NN PN IN PN NN NN NN CD IN PN NN CD PN KAN
PRO PN PN
DT VB PN PN
PRO PN PN
NN VB IN SYM NN DT VB SYM RB VB NN VB VB IN NN JJ VB NN IN VB NN JJ KAN
PRO PN
NN RPN VB IN NN PN VB IN NN VB_JJ NN IN NN DT IN JJ IN RB VB NN KAN
PRO NN PN
PRO NN PN PN
IN NN JJ CC NN DT VB NN RPN JJ VB VB IN NN NN NN NN NN CD IN NN NN CD VCOM KAN
NN AUX JJ IN PRO RB AUX VB NN JJ KAN
PRO PN
PRO PN PN
CC PRO VB IN JJ NN VB NN RB PA RB AUX VB NN IN NN NN RB JJ NN RB VB VB NN IN VB CD NN SYM CC NN PRO VB RB RB CC VB JJ NN VB NN IN NN RB KAN
PRO PN PN
PRO NN PN
PRO PN PN
PRO PN PN
PRO PN PN
RB NN IN PRO RPN VB DT VB VB IN VB JJ RB NN DT VB VB IN NN IN NN SYM
DT VB PN PN
JJ DBL VB IN CC PRO CD VB IN SYM IN VB NN DT RB RB AUX VB VB PA SYM PRO DT AUX VB VB NN VB JJ DBL CD NN KAN
PRO PN PN
PRO PN PN
PRO PN PN
PRO PN PN PN
CD SYM NN NN NN
PRO NN PN PN
PRO PN PN
PRO PN
CD SYM NN NN JJ IN NN IN NN
PRO VB NN IN NN IN PRO VB VB RB JJ RB JJ KAN NN PN VB NN NN NN NN NN IN NN CC NN IN JJ NN
PRO PN
CC PRO NN NN NN IN NN JJ NN AUX VB PN PN IN NN DT IN JJ DBL DT VB NN PN CD M RPN AUX VB NN VB NN VB_JJ IN NN PN CC VB VB VB IN NN JJ NN CC NN NN KAN
SYM NN CC NN RB VB NN VB IN NN VB NN UH SYM UH SYM RB PRO RB VB NN VB DT NN RPN VB NN DT IN NN NN IN NN NN KAN
PRO VB NN RB RB IN VB NN IN NN NN CC NN IN NN JJ RPN VB NN NN CC NN IN VB IN NN NN CC NN KAN
NN JJ RB VB IN SYM CC NN NN DT AUX VB NN PRO PRO AUX VB IN NN NN CC NN NN PRO AUX VB NN NN PRO NN DT AUX VB IN JJ NN NN CC NN NN PRO AUX VB NN NN PRO PRO DT AUX VB RB VB PRO RB VB PRO IN PA SYM KAN
PRO PN PN
PRO NN PN
PRO PN PN NN NN PN VB IN PRO AUX VB IN NN NN VB_JJ NN NN DT RB RB AUX VB NN NN CC NN VB_JJ VB PRO VB RB RB KAN
RB VB VB VB NN VCOM RB PA KAN
PRO PN
NN NN PN
CC RB VB VB NN VB PRO VB VB NN VB RB VCOM KAN
NN PN PN
PRO NN PN PN
PRO NN PN
PN VB IN SYM PRO VB NN RB SYM KAN
IN NN RPN NN NN DT VB IN NN NN NN AUX VB NN JJ DBL RB IN VB NN IN NN NN IN JJ KAN
NN NN RPN NN CD NN DT VB VB IN NN NN NN CD JJ KAN
PRO NN PN
PRO PN PN
PN PN NN NN NN PN NN CC VB_JJ NN NN PN AUX VB IN SYM SYM NN CC NN JJ DBL DT DT VB IN NN NN RB VB IN NN JJ IN NN NN KAN
PRO PN
CC IN NN JJ SYM JJ NN VB JJ JJ NN IN NN IN NN RPN PRO VB IN RB VB RB IN CD NN RB NN DT VB JJ NN CD RB KAN
PRO PN
DT VB PN
IN NN NN IN NN PN IN NN RPN VB NN IN NN NN CD NN IN PN PRO AUX VB IN SYM SYM PRO AUX VB NN VB RB IN QT NN IN NN RB RB NN VB RB VB RB IN NN DT CC VB NN IN NN NN NN NN RB IN NN NN RPN VB IN NN RPN NN NN DT VB IN VB SYM KAN
PRO PN
PRO PN
PRO NN PN PN
CC PRO PRO VB IN VB NN DT VB VB NN JJ RB CC NN PRO AUX VB NN IN NN IN NN RPN VB KAN
PRO PN PN
PRO PN
PRO PN PN
DT VB PN PN PN
PRO PN
PRO PN PN PN
PRO PN PN PN
PRO VB IN SYM SYM PRO AUX VB NN DT RB PRO IN PRO VB IN PN VB NN JJ KAN
PRO PN
PRO NN PN
PRO PN PN
PRO PN
PRO PN
PRO RB VB IN NN NN VB PRO RB JJ RB CC PRO AUX VB IN PRO VB NN IN NN IN NN PRO KAN
PRO PN
PRO PN PN
SYM NN NN JJ NN IN NN NN PN IN NN IN NN NN PN
PRO PN PN
PRO PN PN
PRO PN
PRO PN
VB VB IN IN VB VB IN NN VB VB VB NN IN CD NN IN CD NN VB NN CD NN IN NN NN NN NN NN JJ RB RB VB NN PN CC RB RB VB NN PN KAN
DT VB PN PN
NN JJ VB IN RB NN IN PRO VB CC RB VB IN NN KAN
PRO PN PN PN PN
PRO PN PN
PRO NN PN PN
PRO NN PN
PRO PN VB IN SYM SYM RB PRO IN NN IN PRO PA KAN SYM
PRO PN
PRO PN
NN RB VB VB IN RB VB RB VB NN DT
PRO PN
NN CD NN VB NN IN PRO VB NN IN NN PN AUX VB IN SYM SYM PRO RB AUX VB NN DT PA VB RB NN NN DT NN RB IN PRO VB PRO PN PN PRO PN PN JJ RB AUX VB PRO RB PRO IN VB VB NN RB IN IN NN NN PN DT PRO JJ JJ RB IN KAN
PRO PN
DT VB PN
IN JJ JJ PA NN PRO PN VB VB NN RB VB PRO PN NN JJ VB RB VB PRO PN IN NN
DT VB PN
PRO PN
PRO NN PN PN
DT VB PN PN
DT VB PN PN
PRO NN PN PN PN
PRO PN
DT VB PN PN
DT VB PN PN
IN NN JJ PRO VB PRO VB NN JJ IN NN CD NN NN CC NN NN NN CD PN PN KAN
PRO PN PN
VB VB IN PN VB VB NN JJ NN CD CD PN PN SYM IN CD CD PN SYM IN PN IN NN IN NN DT RB IN JJ NN JJ AUX VB IN NN AUX VB NN CD CD PN PN SYM IN CD CD PN SYM RB IN VB NN IN NN VB_JJ DT KAN
PRO PN PN PN
PRO NN PN PN PN
PRO PN PN PN
PRO PN PN PN
PRO PN PN
PRO PN
PRO PN PN
PRO PN PN PN
PRO NN PN PN
PRO PN
PRO PN PN
PRO PN
PRO PN PN PN
PRO PN PN
PRO PN PN
PRO PN PN
DT VB PN
IN NN RPN PRO VB PRO AUX AUX PRO VB IN RB RB KAN
VB PRO PN VB_JJ NN VB RB
IN IN NN PN PN RB VB NN JJ NN DT IN NN RB KAN
PRO PN PN
PRO NN PN PN PN
IN NN CD PN NN NN CC NN DT CD M VB NN RB NN IN NN NN NN PN PN CC VB VB NN DT VB KAN
PRO PN
DT VB PN PN
PRO NN PN
PRO NN PN
NN NN PN IN NN PN NN AUX VB NN VB NN VB_JJ DT RPN VB JJ NN NN NN CD NN IN NN VB_JJ NN VB_JJ NN JJ VB_JJ NN VB_JJ NN CC NN RPN VB IN JJ CD NN JJ KAN
PRO PN
NN DT AUX VB RB IN SYM SYM NN PN AUX VB PN IN NN JJ IN NN NN NN VB_JJ CC NN VB_JJ CC NN SYM KAN
PRO PN PN
PRO AUX VB IN SYM NN PN NN VB JJ KAN
DT VB PN PN
PRO PN PN
PRO NN PN PN
RB NN PN RB VB VB NN IN NN IN NN RB VB CC NN JJ DBL VB NN VB IN NN IN PRO DT IN NN PN CC RB IN NN RPN NN IN NN DT VB VB NN JJ RB IN NN JJ KAN
PN SYM NN VB_JJ CD VB IN NN NN CD IN JJ NN IN NN NN VB_JJ NN NN IN NN JJ AUX VB IN NN CC NN JJ IN NN CC NN IN NN NN IN NN VB RB NN VB NN JJ JJ NN RPN NN DT RB VB NN IN NN NN NN NN JJ CC NN NN VB_JJ NN RB KAN
DT NN PRO PN VB NN PN VB VB VB NN PN
PRO PN PN
PRO PN
DT VB PN
IN PRO RB VB NN IN RB RPN NN RB RB VB VB IN PRO RPN AUX VB CC VB IN NN CD PN CC NN CD CC NN CD PN CC RB VB NN IN NN CC VB_JJ PRO DT RPN VB IN NN DT SYM KAN
NN NN CD IN PN NN NN CD NN PRO PN RB JJ KAN
PRO PN
PRO PN PN
PRO PN PN
NN NN NN IN NN PN RB VB VB IN NN RPN RB VB RB IN VB IN NN NN NN IN NN CD VB_JJ IN NN DT RPN AUX VB VB NN CC NN NN IN PN KAN
PRO NN PN
PRO PN PN
PRO NN PN
PRO NN PN PN
PRO PN
NN NN VB_JJ NN PRO PN PN VB IN PRO AUX VB NN DT VB IN NN NN IN VB CC VB VB NN CC NN PN JJ RB VB NN IN PN JJ KAN
PRO PN PN PN
DT VB PN PN
NN CD VB NN JJ NN NN NN NN ETC
DT VB PN PN
NN CC NN VB RB VB RB IN VB NN NN CD VB VB IN NN NN VB RB VB NN CC NN VB NN RB VB VB NN RB NN VB NN IN SYM UH NN PRO DT CD RB VB PRO NN NN RB RB VB VB RB IN PRO PRO AUX VB PRO PA SYM KAN
PRO PN
PRO PN
PRO PN PN
PRO PN PN
PRO NN PN PN
PRO PN PN
PRO PN
JJ DT PRO PN PN AUX VB IN NN NN VB_JJ NN RPN RB VB IN PRO VB VB VB IN NN PRO IN PRO IN VB IN PRO RPN PRO VB IN IN NN VB_JJ IN PRO RB PRO AUX VB VB PRO IN NN PRO KAN
IN NN RB VB VB VB IN PRO PN
NN CD IN NN VB VB IN JJ NN
RB IN NN NN NN RB IN VB NN NN DT PN VB IN NN IN PRO VB CD NN NN PN VB IN NN NN CD VB CD NN KAN
NN NN VB_JJ NN CC NN RPN VB NN VB IN IN NN VB IN NN CC RB RB AUX VB NN IN NN DT RB PA
PRO PN PN
NN DT NN RB PRO VB JJ CD NN PRO RB PRO VB NN JJ JJ NN RB RB KAN
PRO NN PN PN
DT VB PN PN
PRO PN PN
PRO NN PN
NN VB NN IN NN NN IN NN PN PN NN RB RB RB VB IN PRO VB_JJ PRO VB CC PRO VB
PRO PN
PRO NN PN PN
PRO PN
PRO PN
PRO PN
CC RB NN PRO DT AUX RB VB NN IN NN NN IN NN IN VB NN IN PRO KAN
PRO PN PN
PRO PN PN
PRO PN
CC VB NN RB DT RB VB NN IN NN PRO VB NN VCOM CC NN VB NN IN NN NN CC PRO VB NN VB KAN
PRO PN PN
PRO NN PN PN
DT VB PN
PRO NN PN PN
PRO PN
PRO PN
DT VB PN PN
PRO PN
SYM PRO VB NN VB_JJ NN NN DT RPN AUX VB NN IN NN NN IN NN PN DT IN NN NN NN PN KAN
PRO PN PN
NN NN DT CD DT VB_JJ PRO VB RB NN NN VB_JJ NN RPN VB NN JJ CD NN KAN
PRO NN PN PN
PRO PN PN PN
VB PRO VB PRO RB NN DBL VB KAN
PRO AUX VB RB IN SYM SYM NN RPN NN VB IN NN RB VB PRO VB IN NN VB_JJ IN NN NN NN RB JJ NN CC JJ VB JJ NN PN PN CC RB VB VB NN IN NN IN NN NN KAN SYM
PRO PN
PRO NN PN PN
IN NN DT RPN AUX VB PN VB NN JJ RB IN NN PN NN CC PN RPN NN RB RB VB VB NN RB VB JJ PN PN CC PN KAN
PRO PN PN
PRO PN PN NN NN CD IN AB CC VB_JJ NN IN NN DT RPN IN NN NN AUX VB PN PN IN NN IN AB AUX VB NN IN JJ NN IN AB CC NN RB KAN
NN CD M VB VB VB IN NN AUX VB NN JJ IN NN NN KAN
PRO PN PN
DT VB PN
PRO NN PN PN
PRO PN PN
PRO NN PN
CC NN JJ RB VB NN JJ RB JJ NN DT VB VB IN NN CD NN CD NN KAN
PRO PN
RB NN VCOM NN NN DT PRO VB VB NN RPN VB NN SYM KAN
PRO PN PN
NN IN NN DT VB NN IN NN PN IN NN NN DT VB NN CD VB IN NN PN KAN
RB VB VB PRO RB RB PA KAN
PRO PN PN
PRO PN PN
NN NN NN PN CC NN NN NN CC NN NN RPN VB IN PRO PN PN JJ NN JJ NN NN AUX VB NN VB_JJ NN NN NN CD NN IN NN NN NN NN PN RPN VB NN VB IN NN PN NN PN NN PN IN PN NN CD PN KAN
PRO PN VB IN SYM VB NN JJ NN JJ VB NN NN VB NN SYM
DT VB PN
PRO NN PN
PRO NN PN
NN DT AUX VB RB IN SYM SYM CC VB VB IN VB NN IN NN NN NN RPN VB NN IN NN IN NN IN NN NN RPN VB NN NN DT SYM KAN
NN CD IN NN RPN VB PRO CC VB NN VB VB VB KAN
PRO NN PN PN PN
PRO PN
PRO PN
CC NN VB IN NN VB RB RB RB JJ JJ IN PA RB PRO VB IN NN VB_JJ NN DT IN NN NN VB VB RB KAN
NN IN NN JJ VB NN RB JJ IN NN DT VB VB IN JJ IN NN VB_JJ NN IN PRO NN NN PN CC PRO NN NN PN PN IN IN CD NN JJ KAN
PRO VB IN SYM SYM NN NN CD M NN NN VB IN PN RB CC NN AUX VB VB NN IN PRO KAN
SYM
PRO PN PN
PRO NN PN
PRO PN
NN RB VB NN VB IN NN NN NN RB PRO VB VB NN JJ NN IN NN NN RPN NN VB IN KAN
IN NN NN NN VB NN JJ IN NN NN JJ RB IN NN NN KAN
JJ JJ RB DT VB PRO AUX VB NN NN CD IN NN NN NN IN NN CD PN NN CD IN AUX VB NN PN NN CD IN NN NN DT KAN
DT VB PN PN
PRO PN
PRO PN
NN AUX VB IN IN NN CD NN NN DT IN NN IN NN NN VB VB NN CD SYM CD NN KAN
DT VB PN PN
PRO PN
CC NN NN VB NN NN IN NN CD RPN VB NN JJ IN NN DT PRO VB NN IN QT AUX VB NN PRO PA SYM KAN
PRO PN
PRO PN
CC PRO PA PRO AUX VB IN PRO JJ VB NN NN CC NN RPN AUX VB IN NN PN PN IN NN VB_JJ VB JJ VB NN KAN
PRO NN PN PN
PRO PN PN
CC NN CD VB NN NN PN SYM VB IN NN NN JJ DBL DT RB RB VB NN NN NN JJ PA RB JJ JJ RB DT VB VB VB NN CD RPN NN PN VB VB VB NN RB CC JJ SYM KAN
VB_JJ IN VB VCOM NN NN PN AUX VB IN SYM SYM PRO VB NN PN KAN
PRO PN PN
PRO PN PN
PRO PN
PRO PN PN
IN NN DT NN JJ RPN JJ NN NN CC NN JJ CD M AUX VB VB VB NN NN IN NN VB_JJ DT DT KAN
PRO PN PN PN
PRO PN PN
PRO NN PN PN
IN DT PRO RPN VB VB DT VB NN DT RB VB VB RB VB NN DT JJ VB IN VB VB VB VB IN NN RB
PRO NN PN PN
IN NN DT PRO VB VB NN NN IN CD RB M VB NN RB NN NN CD NN IN VB NN IN NN NN NN CD CC NN NN NN NN JJ NN VB_JJ NN NN IN PN KAN
CD SYM NN PN IN JJ NN NN JJ NN NN NN PN SYM
PRO PN PN PN
PRO NN PN PN
PRO NN PN PN
PRO PN
CC CC CC VB NN RB RB RB DT PN CC PN VB IN NN IN NN IN NN AUX VB VB NN JJ RB VB VB VB PN KAN
PRO PN PN
PRO PN PN PN
DT VB PN PN
PRO PN PN
CC VB_JJ NN JJ NN CD VB IN NN PN PN PN CC NN PN PN NN CD PN PN CC NN PN PN IN NN CD PN PN CC NN PN PN RPN DT CD NN DT IN NN NN NN RB KAN
PRO PN PN PN
PRO NN PN
PRO PN PN
PRO NN PN PN
NN IN NN VB IN NN IN NN RB JJ CC PRO AUX VB PRO VB NN VB_JJ CC VB NN CC PRO PRO RB AUX VB NN RPN VB PRO VB SYM KAN
PRO PN
NN NN CD IN NN
PRO PN VB IN NN NN DBL RPN VB NN VB IN RB IN NN IN VB VB NN SYM VB SYM IN NN IN PRO KAN
NN IN PN VB NN DT IN NN PN IN NN PN KAN
PRO PN
PRO NN NN RB AUX VB IN NN DT VB IN NN JJ IN VB IN RB VB NN VB IN NN PN RB PA KAN
NN IN SYM SYM PRO AUX VB IN NN VB_JJ IN PRO IN VB VB IN NN CC NN NN NN NN IN DT NN VB_JJ IN NN PN KAN SYM
PRO PN
PRO PN
PRO PN PN
IN NN RPN VB NN JJ IN NN JJ IN VB DT IN NN IN NN JJ NN CC NN IN VB NN DT RB RB VB NN DT PA KAN
PRO PN PN
PRO NN PN PN
PRO NN PN PN
NN DT NN VB IN NN AUX VB KAN
PRO PN PN PN
DT VB PN
PRO PN PN NN NN PN PN RB AUX VB RB IN NN NN NN CD NN AUX VB NN NN NN RPN NN AUX VB NN PRO IN VB NN VB NN KAN
PRO PN
PRO PN PN
